sudo: false
language: node_js
env:
  - CLI_TIMEOUT=10000
node_js:
  - "6.0"
  - "8.10"
#  - "stable"
before_script:
  - npm run browser
  - git clone --depth=50 --branch=backtick https://github.com/shexSpec/shexTest.git ../shexTest
script:
  - npm run test && TEST_cli=true mocha -C -R dot test/cli-test.js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
