sudo: false
language: node_js
env:
  - CLI_TIMEOUT=10000
node_js:
  - "6.0"
  - "8.0"
  - "stable"
script:
  - npm run test-all
after_success:
  - npm run coverage:report
cache:
  directories:
    - node_modules
before_script:
  - npm run browser
